[tool.poetry]
name = "footypy"
version = "0.1.0"
description = "A python package for Australian Rules Football data and statistics."
authors = ["Sam Pardy"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.3"
numpy = "^2.1.3"
pandas = "^2.2.3"
beautifulsoup4 = "^4.12.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
